### ISSUE TITLE
Sysbench oltp_point_select regression with new request-batch mechanism

### ISSUE THREAD

**Issue by youjiali1995** [tikv/tikv#10046]
## Description
[`enable-request-batch=true`](https://github.com/tikv/tikv/pull/7878) results in about 5% throughput regression in `oltp_point_select` and the throughput is more unstable than turning it off.

The informal benchmark result is
Version | threads 500*1 | CPU Usage | 500*3 | Usage
-- | -- | -- | -- | --
v4.0.12 TiDB + v4.0.12 TiKV | 137273 | 1520%(TiDB) + 3*350%(TiKV storage pool) | 345075 | 3\*1320% + 3\*740%
v4.0.12 TiDB + v5.0 TiKV | 132203 | 1520% + 3*350% | 322585 | 3\*1200% + 3\*600%
v4.0.12 TiDB + v5.0 TiKV disable request batch | 134747 | 1500% + 3*400% | 344224 | 3\*1300% + 3\*850%

## Topology
3 TiDB: c5.4xlarge
3 TiKV: i3.4xlarge
3 PD: m5.xlarge
1 haproxy: c5.4xlarge
1 sysbench: c5.9xlarge

### TiDB
version: 5.0.0

```yaml
log.level: “error”
performance.max-procs: 20
prepared-plan-cache.enabled: true
tikv-client.max-batch-wait-time: 2000000
```
### TiKV
version: 5.0.0

```yaml
storage.scheduler-worker-pool-size: 5
raftstore.store-pool-size: 3
raftstore.apply-pool-size: 3
rocksdb.max-background-jobs: 3
raftdb.max-background-jobs: 3
raftdb.allow-concurrent-memtable-write: true
server.request-batch-enable-cross-command: false
server.grpc-concurrency: 6
readpool.unified.min-thread-count: 5
readpool.unified.max-thread-count: 20
readpool.storage.normal-concurrency: 10
pessimistic-txn.pipelined: true
```
