### ISSUE TITLE
5.1.0  thread 'sched-worker-pool-0' has overflowed its stack fatal runtime error: stack overflow

### ISSUE THREAD

**Issue by darren** [tikv/tikv#10460]
### What version of TiKV are you using?

```
TiKV 
Release Version:   5.1.0
Edition:           Community
Git Commit Hash:   5a2d13fe14a31edee3c98715ac575b1663c0df47
Git Commit Branch: release-5.1
UTC Build Time:    2021-06-25 03:02:28
Rust Version:      rustc 1.53.0-nightly (16bf626a3 2021-04-14)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           release
```

config:

```toml
[server]
log-level = "info"
[metric]
interval = "15s"
address = ""
job = "tikv"
[raftstore]
sync-log = true
raft-base-tick-interval = "2s"
[storage.block-cache]
shared = true
capacity = "2GB"
[pd]
[rocksdb]
compaction-readahead-size = "8MB"
[rocksdb.defaultcf]
compression-per-level = ["no", "snappy", "lz4", "lz4", "lz4", "zstd", "zstd"]
max-write-buffer-number = 15
[storage]
scheduler-worker-pool-size = 8
reserve-space = "0"
```
### What operating system and CPU are you using?

```
processor	: 31
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2680 0 @ 2.70GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2201.343
cache size	: 20480 KB
physical id	: 1
siblings	: 16
core id		: 7
cpu cores	: 8
apicid		: 47
initial apicid	: 47
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts
bogomips	: 5405.04
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```
### What did you expect?
no fatal exit

### What did happened?

thread 'sched-worker-pool-0' has overflowed its stack fatal runtime error: stack overflow
