### ISSUE TITLE
ratelimiter: sst_importer local write IO is not limited

### ISSUE THREAD

**Issue by andylokandy** [tikv/tikv#10581]
### What version of TiKV are you using?

master https://github.com/tikv/tikv/commit/ed5c5b312cc9da3801fa2e6c7dcf5b73e017bf8e

### What is happend?

The IO rate limiter claimed to be able to limit all disk IO on TiKV including sst_importer. But with this config, the lightning using the local backend will not be limited as expected:

```toml
[storage.io-rate-limit]
max-bytes-per-sec = "1000MB"
import-priority = "low"
```
