### ISSUE TITLE
metrics samples too much for tikv_threads_io_bytes_total & tikv_thread_cpu_seconds_total 

### ISSUE THREAD

**Issue by slow-zhang** [tikv/tikv#10608]
tikv_threads_io_bytes_total & tikv_thread_cpu_seconds_total for 30 tikv instance need ~7M sample 

![image](https://user-images.githubusercontent.com/24769636/126599068-1be4326a-ea5b-40c6-a6d5-0fd30cabbc3e.png)

**Comment by slow-zhang** [comment]
is there some way to decrease the sample amounts?

**Comment by zhongzc** [comment]
It seems to be a bug. Can you provide more information about your environment and the version of TiKV?

**Comment by slow-zhang** [comment]
thanks for the quick reply. we use ti-operator setup a v4.0.9 tikv+pd. here is the tikv config

```toml
      [server]
        grpc-keepalive-time="12s"
      [rocksdb]
        # we set this to avoid the following error in some Kubernetes clusters:
        # "the maximum number of open file descriptors is too small, got 1024, expect greater or equal to 82920"
        max-open-files=82920
        rate-bytes-per-sec="60MB"
        rate-limiter-mode=3
      [rocksdb.titan]
        enabled=true
        max-background-gc=1
      [rocksdb.defaultcf]
        level0-slowdown-writes-trigger=80
        level0-stop-writes-trigger=100
        max-write-buffer-number=30
      [rocksdb.defaultcf.titan]
        blob-file-compression="zstd"
        blob-cache-size="40GB"
      [readpool.storage]
        use-unified-pool=false
      [readpool.coprocessor]
        use-unified-pool=true
      [readpool.unified]
        max-thread-count=6
      [raftdb.defaultcf]
        level0-slowdown-writes-trigger=60
        level0-stop-writes-trigger=80
        max-write-buffer-number=30
        compression-per-level= ["lz4","lz4","lz4","lz4","lz4","zstd","zstd"]
      [raftdb]
        max-open-files=82920
        max-background-jobs=10
        max-sub-compactions=6
      [raftstore]
        raft-base-tick-interval="3s"
        raft-store-max-leader-lease="27s"
        raft-max-inflight-msgs=1024
```
