### ISSUE TITLE
copr_plugin: Disable coprocessor plugin if the plugin folder is not explictly sepcified in config

### ISSUE THREAD

**Issue by andylokandy** [tikv/tikv#10855]
## Feature Request

Currently, TiKV loads all plugins from `./coprocessors` if the plugin folder is not explicitly specified in config, which may not be a good thing for security. And as stated in config:

https://github.com/tikv/tikv/blob/19e4d00ad7965681b5139cd71c7eaf8290cc22ce/etc/config-template.toml#L445-L450

Whether specifying the plugin folder or not enables or disenables the auto-loading, which seems puzzling. So I suggest changing the config as so:

```toml
[coprocessor-v2]
# Path to the directory where compiled coprocessor plugins are located.
# Plugins in this directory will be automatically loaded by TiKV.
# If the config value is not set, the coprocessor plugin will be disabled.
coprocessor-plugin-directory = "./coprocessors"
```
