### ISSUE TITLE
Configuration guidance for docker/k8s and servers with small amount of resource

### ISSUE THREAD

**Issue by xpepermint** [tikv/tikv#10908]
There's a lot of configuration keys that we can twist but it looks like nothing works for a very small server setup. In k8s you have to accurately predict the CPU and RAM usage to prevent pods to go down (usually because of OOM). This seems very difficult.
 
Could someone please post some recommendations on how to keep the resource low? I'd like to be able to run TiDB (TiKV) in a pod with let say 512MB RAM and 0.1 CPU. What configuration would work? What parameters I should set and how?

**Comment by xpepermint** [comment]
It seems that whatever I set, the memory keeps increasing and has no effect. 

Example:
```yaml
# Ref: https://raw.githubusercontent.com/pingcap/tidb-operator/master/examples/basic/tidb-cluster.yaml
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: tidb
  namespace: tidb-cluster
spec:
  version: "v5.2.0"
  enableDynamicConfiguration: true
  ...
  tikv:
    baseImage: pingcap/tikv
    # Ref: https://docs.pingcap.com/tidb/stable/tikv-configuration-file
    config: |
      memory-usage-limit = "16MB"
      [server]
      grpc-memory-pool-quota = "1MB"
      [storage]
      reserve-space = "0MB"
      [storage.block-cache]
      shared = true
      capacity = "8MB"
      [rocksdb]
      max-open-files = 256
      [rocksdb.defaultcf]
      write-buffer-size = "1MB"
      max-write-buffer-number = 1
      [rocksdb.writecf]
      write-buffer-size = "1MB"
      max-write-buffer-number = 1
      [rocksdb.lockcf]
      write-buffer-size = "1MB"
      max-write-buffer-number = 1
      [raftdb.defaultcf]
      write-buffer-size = "1MB"
      max-write-buffer-number = 1
      [raftdb]
      max-open-files = 256
    replicas: 1
    requests:
      storage: "2Gi"
      memory: "1024Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "100m"

# # Sufficient AWS instance type: 3 x t3.medium
# # Ref: https://github.com/pingcap/tidb-operator/blob/master/examples/advanced/tidb-cluster.yaml
# apiVersion: pingcap.com/v1alpha1
# kind: TidbCluster
# metadata:
#   name: tidb
#   namespace: tidb-cluster
# spec:
#   version: "v5.2.0"
#   timezone: UTC
#   configUpdateStrategy: RollingUpdate
#   imagePullPolicy: IfNotPresent
#   enablePVReclaim: false
#   pvReclaimPolicy: Delete
#   storageClassName: kops-csi-1-21
#   discovery:
#     limits:
#       cpu: 200m
#       memory: 32Mi
#   enableDynamicConfiguration: true
#   pd:
#     baseImage: pingcap/pd
#     # Ref: https://docs.pingcap.com/tidb/stable/pd-configuration-file
#     config: |
#       # Max metadata size (8GB)
#       quota-backend-bytes = 8589934592
#       # Log level
#       level = DEBUG
#     replicas: 3
#     maxFailoverCount: 3
#     requests:
#       storage: 10Gi
#     # limits:
#     #   cpu: 600m
#     #   memory: 256Mi
#     storageClassName: default
#   tidb:
#     baseImage: pingcap/tidb
#     # Ref: https://docs.pingcap.com/tidb/stable/tidb-configuration-file
#     config: |
#       # Concurent sessions.
#       token-limit = 5
#       # Max memory per SQL statement (16MB; mem-quota-query * token-limit = POTENTIAL)
#       mem-quota-query = 16777216
#       # Max storage per SQL statement (32MB; mem-quota-query * token-limit = POTENTIAL) 
#       tmp-storage-quota = 33554432
#       # Customize version string
#       server-version = "5.7.${mysql_latest_minor_version}-Nibbstack-0.01"
#       # Max server connections
#       max-server-connections = 5
#       # Only IP4
#       enable-tcp4-only = true
#       # Log level
#       level = "debug"
#       # Mark expensive statements
#       expensive-threshold = 1000
#       # Log TTL in days
#       max-days = 30
#       # Max number of CPUs
#       max-procs = 1
#       # Max RAM (512MB)
#       server-memory-quota = 536870912
#       # Max transaction duration (30s)
#       max-txn-ttl = 30000
#       # Max statements per transaction
#       stmt-count-limit = 20
#       # Max size of each row in transaction (1MB)
#       txn-entry-size-limit = 1048576
#       # Max data limit of a transaction (1MB)
#       txn-total-size-limit = 1048576
#       # Disable cache for nested JOINs
#       nested-loop-join-cache-capacity = 0
#     replicas: 2
#     maxFailoverCount: 3
#     # limits:
#     #   cpu: 300m
#     #   memory: 512Mi
#     service:
#       # Ref: https://docs.pingcap.com/tidb-in-kubernetes/stable/access-tidb
#       type: NodePort
#       externalTrafficPolicy: Cluster
#       mysqlNodePort: 30020
#       statusNodePort: 30040
#       exposeStatus: true
#     separateSlowLog: true
#   tikv:
#     baseImage: pingcap/tikv
#     # Ref: https://docs.pingcap.com/tidb/stable/tikv-configuration-file
#     config: |
#       prevote = true
#     replicas: 1
#     maxFailoverCount: 3
#     requests:
#       storage: 10Gi
#     # limits:
#     #   cpu: 300m
#     #   memory: 1024Mi
#     separateRocksDBLog: true
#     separateRaftLog: true
#     storageClassName: default
#     recoverFailover: true
#   tiflash:
#     baseImage: pingcap/tiflash
#     replicas: 1
#     # limits:
#     #   cpu: 600m
#     #   memory: 2048Mi
#     maxFailoverCount: 3
#     storageClaims: 
#     - resources:
#         requests:
#           storage: 10Gi
#       storageClassName: default
#     recoverFailover: true
#     # Ref: https://docs.pingcap.com/tidb/dev/tiflash-configuration
#     config:
#       config: {}
```
