### ISSUE TITLE
v5.2.2: 2 tikvs oom and can't start after 1 hours 

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#11581]
### What version of TiKV are you using?

```bash
/ # /tikv-server -V
TiKV
Release Version:   5.2.2
Edition:           Community
Git Commit Hash:   7acaec5d9c809439b9b0017711f114b44ffd9a49
Git Commit Branch: heads/refs/tags/v5.2.2
UTC Build Time:    2021-10-25 12:03:38
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release
```

### What operating system and CPU are you using?

k8s config.
```yaml
  tikv:
    baseImage: registry-mirror.pingcap.net/pingcap/tikv
    config: |
      log-file = "/var/lib/tikv/log/tikv.log"

      [storage]
        reserve-space = "0MB"
    dataSubDir: data
    image: pingcap/tikv:nightly
    limits:
      cpu: "8"
      memory: 16Gi
    maxFailoverCount: 3
    replicas: 4
    requests:
      cpu: "8"
      memory: 16Gi
      storage: 40Gi
    storageVolumes:
    - mountPath: /var/lib/tikv/log
      name: log
      storageClassName: local-path
      storageSize: 10Gi
```

### Steps to reproduce

```bash
ginkgo -focus "oltp_fun_001" -- TiDB-OLTP -workloadType sysbench_bulk_insert -sysbenchThreads 32
```

### What did you expect?
Everything works fine.

### What did happened?
```
# tikv 0 and tikv 3 restarts more than 10 times.

 k8 get pod
NAME                            READY   STATUS             RESTARTS   AGE
benchtoolset-0                  1/1     Running            0          27h
br-0                            1/1     Running            0          27h
tc-discovery-7444c69cf5-5g5nq   1/1     Running            0          27h
tc-monitor-0                    3/3     Running            0          27h
tc-pd-0                         1/1     Running            0          27h
tc-tidb-0                       1/1     Running            0          27h
tc-tidb-1                       1/1     Running            0          27h
tc-tikv-0                       0/1     CrashLoopBackOff   16         27h
tc-tikv-1                       1/1     Running            0          27h
tc-tikv-2                       1/1     Running            0          27h
tc-tikv-3                       0/1     CrashLoopBackOff   15         27h
```
![image](https://user-images.githubusercontent.com/9443637/144806506-65f6b7c5-d3b3-4e4d-b3e3-9bf9419bf293.png)

Logs can be got using this testbed in loki and minio:
testbed-oltp-hm-kk9jg
