### ISSUE TITLE
tikv keep oom on arm64 k8s deployments during br restore

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#11670]
### What version of TiKV are you using?

```
MySQL [(none)]> select distinct type,version,git_hash from information_schema.cluster_info;
+------+-------------------------+------------------------------------------+
| type | version                 | git_hash                                 |
+------+-------------------------+------------------------------------------+
| pd   | 5.4.0-alpha-49-geba75c3 | eba75c3080a0db2d5edda7a2a8628e3a08c1af87 |
| tidb | 5.4.0-alpha             | 755553660e6036ead13d1f0aa271eaf59d939fbd |
| tikv | 5.4.0-alpha             | 7eeff52ec2f9494a24c712479720bbcf5e9d85dd |
+------+-------------------------+------------------------------------------+
3 rows in set (0.017 sec)
```
### What operating system and CPU are you using?

arm64 linux

### Steps to reproduce

```
restore the ycsb dateset
    br restore db --db=test --pd "pd-peer:12379" \
        --storage "s3://ycsb-100m-v5.0.0" \
        --s3.endpoint "xyz.com" \
        --send-credentials-to-tikv=true \
                --check-requirements=false
```
### What did you expect?
restore successfully

### What did happened?
tikv keep oom and br restore fail
why tikv use 62G memory immediate just after startup.
For the tikv pod, 64G memory is allocated. memory_limit is set to 62GB. 
```
  arch: arm64
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tiup/deploy"
  data_dir: "/tiup/data"
  resource_control:
    memory_limit: "62G"
monitored:
  node_exporter_port: 19100
  blackbox_exporter_port: 19115
server_configs:
  pd: {}
  tidb: {mem-quota-query: 64424509440, prepared-plan-cache: {enabled: true}}
  tikv: {"storage.block-cache.capacity": 30GB}
```

![image](https://user-images.githubusercontent.com/2316425/146404015-6041acac-2dc1-4638-8c62-2c52b343dcbd.png)

![image](https://user-images.githubusercontent.com/2316425/146404088-f14d465e-5098-4496-b257-2af2eb476812.png)
