### ISSUE TITLE
[Dynamic Regions] TPCC 1K 7d stability test: QPS drops dramatically when partitioned-raft-kv is enabled compared to baseline

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#14460]
### What version of TiKV are you using?

```
[root@tikv-6-0 bin]# ./tikv-server --version
TiKV
Release Version:   7.0.0
Edition:           Community
Git Commit Hash:   38d6d6264e4ce25e3fe780e03b879c04890ca37b
Git Commit Branch: heads/refs/tags/v7.0.0
UTC Build Time:    2023-03-24 09:40:13
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
```

### What operating system and CPU are you using?

x86
### Steps to reproduce

```
» config set region-schedule-limit 0
Success!
» config set hot-region-schedule-limit 0
Success!
» config set replica-schedule-limit 0
Success!
  tikv:
    import.num-threads: 64
    raft-engine:
      purge-threshold: 200GB
    raftstore:
      store-io-pool-size: 4
    rocksdb:
      defaultcf:
        compression-per-level:
        - lz4
        - lz4
        - lz4
        - lz4
        - lz4
        - zstd
        - zstd
      write-buffer-limit: 8GiB
      writecf:
        compression-per-level:
        - lz4
        - lz4
        - lz4
        - lz4
        - lz4
        - zstd
        - zstd
    server:
      snap-io-max-bytes-per-sec: 50MiB
    storage:
      engine: partitioned-raft-kv
    storage.block-cache.capacity: 30GB
```

go-tpc command, tpcc 1k warehouse
```
go-tpc tpcc --host lb.release-perftest-amd64-tpcc-stability-7d-tps-1661283-1-661 -P4000 --warehouses 1000 run -D tpcc -T 200 --time 168h0m0s --ignore-error
```

### What did you expect?
Baseline QPS trend
![image](https://user-images.githubusercontent.com/2316425/227772580-3f0f925b-dcc6-4d52-b1b5-84d190d29989.png)

### What did happened?
![image](https://user-images.githubusercontent.com/2316425/227772876-1356405b-9d69-4e5d-a334-73c6ecab834c.png)
![image](https://user-images.githubusercontent.com/2316425/227772671-445ab00d-5667-443a-83e2-1ad614aa4b78.png)
![image](https://user-images.githubusercontent.com/2316425/227772709-5756ca2c-5abe-4377-a0aa-02a9f26eb575.png)
![image](https://user-images.githubusercontent.com/2316425/227772738-f7aa253d-fb56-47b5-89fe-6aa00b7f2436.png)
