### ISSUE TITLE
[Dynamic Regions]  raft-engine with v2 is much slower on GCP pd-ssd disk

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#14483]
### What version of TiKV are you using?

v7.0
### What operating system and CPU are you using?

x86
### Steps to reproduce

run a workload simulation with ttl enable

### What did you expect?
no performance degradation

### What did happened?
for v2, when recycling log takes effect, why the performance of raft-engine with v2 does not become better?
when recycling logs take effect, why is the performance of raft engines with v2 much slower compared to v1?
up: v1
down: v2

![image](https://user-images.githubusercontent.com/2316425/228484971-56cd08b4-9019-4b8c-8901-804e4ff00e99.png)

up: v1 QPS: 25k/s, P99: 11.7ms
down: v2 QPS: 19k/s, P99: 15.7ms

![image](https://user-images.githubusercontent.com/2316425/228485258-f4359a56-4116-4f09-a4db-61b9761a2722.png)

TiKV Config on GCP
```
      tikv:
        nodeSelector:
          node.kubernetes.io/instance-type: n2-standard-32
        storageClassName: premium-rwo
        requests:
          storage: 4096Gi
          cpu: 31000m
          # memory: 116Gi
        limits:
          cpu: 32000m
          memory: 64Gi
        replicas: 3
        baseImage: us-west1-docker.pkg.dev/qa-infra-dev/qa/tikv
        storageVolumes:
          - name: log
            storageClassName: local-path
            storageSize: 10Gi
            mountPath: /var/lib/tikv/log
          - name: raft-pv-ssd
            storageClassName: premium-rwo
            storageSize: 500Gi
            mountPath: /var/lib/raft-pv-ssd
        topologySpreadConstraints:
          - topologyKey: topology.kubernetes.io/zone
        config: |
          # FIXME
          # Baseline
          # [cdc]
          #   min-ts-interval = "2s"
          # [coprocessor]
          #   region-split-size = "256MB"
          # [raft-engine]
          #   dir = "/var/lib/raft-pv-ssd/raft-engine"
          #   enable = true
          #   enable-log-recycle = true
          #   purge-threshold = "10GB"
          # [raftstore]
          #   pd-heartbeat-tick-interval = "180s"
          #   raft-max-inflight-msgs = 1024
          #   store-io-pool-size = 1
          #   store-pool-size = 3
          # [resolved-ts]
          #   advance-ts-interval = "10s"
          # [rocksdb]
          #   max-background-jobs = 12
          # [rocksdb.defaultcf]
          #   compression-per-level = ["zstd", "zstd", "zstd", "zstd", "zstd", "zstd", "zstd"]
          # [server]
          #   grpc-concurrency = 8
          # V2
          [raft-engine]
            dir = "/var/lib/raft-pv-ssd/raft-engine"
            purge-threshold = "200GB"
            prefill-for-recycle = true
            enable-log-recycle = true
          [raftstore]
            store-io-pool-size = 4
          [rocksdb]
            write-buffer-limit = "8GiB"
            [rocksdb.defaultcf]
              compression-per-level = ["lz4", "lz4", "lz4", "lz4", "lz4", "zstd", "zstd"]
            [rocksdb.writecf]
              compression-per-level = ["lz4", "lz4", "lz4", "lz4", "lz4", "zstd", "zstd"]
          [server]
            snap-io-max-bytes-per-sec = "50MiB"
          [storage]
            engine = "partitioned-raft-kv"
            reserve-space = "0MB"
```
