### ISSUE TITLE
[Dynamic Regions] TiKV OOM seen after restore data of 4k tables and run workload

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#15257]
### What version of TiKV are you using?
```
[root@upstream-tikv-0 /]# /tikv-server -V
TiKV
Release Version:   7.3.0-alpha
Edition:           Community
Git Commit Hash:   284ff3a9ca144619f5efaa357d6c287f1c669982
Git Commit Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time:    2023-07-31 11:44:07
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-a
zure
Profile:           dist_release
```

### What operating system and CPU are you using?
K8S deployment, TiKV 8C 16G

### Steps to reproduce
1. TiDB cluster 3 TiKV (8C 16G), 2 CDC (8C 16G)
2. run br restore full to restore 600GB data, which contains a big table, and 4000 small tables.
```
/br restore  full "-s" "s3://bigcluster/backup?access-key=xxx&secret-access-key=xxx&endpoint=http%3a%2f%2f172.16.6.5%3a9000&force-path-style=true" "-u" "http://upstream-pd.cdc-kafka-avro-2-workloads-tps-1830435-1-922:2379" "--check-requirements=false"
...
["Full Restore success summary"] [total-ranges=44336] [ranges-succeed=44336] [ranges-failed=0] [split-region=9m39.636390547s] [restore-ranges=30396] [total-take=35m51.661999494s] [total-kv=1423690642] [total-kv-size=666.7GB] [average-speed=309.9MB/s] [restore-data-size(after-compressed)=462.3GB] [Size=462279120463] [BackupTS=442620149300723719] [RestoreTS=443234421570273290]
```

4. create kafka avro changefeed 
```
/cdc  cli  changefeed  create "--server=127.0.0.1:8301" "--sink-uri=kafka://downstream-kafka.cdc-kafka-avro-2-workloads-tps-1830435-1-922:9092/kafka-avro?enable-tidb-extension=true&avro-decimal-handling-mode=string&avro-bigint-unsigned-handling-mode=string&avro-enable-watermark=true&protocol=avro&partition-num=2&replication-factor=2" "--changefeed-id=kafka-avro-enable-extension" "--config=/tmp/changefeed.toml" "--schema-registry=http://schemaregistry.cdc-kafka-avro-2-workloads-tps-1830435-1-922:8081"
```
5. run workloads
```
/workload --tps=1000 --row-count=10000000000  --table-count=1 --thread=0 --workload-type=ycsb_bigtable --database-host=upstream-tidb.cdc-kafka-avro-2-workloads-tps-1830435-1-922 --database-port=4000 --database-user=root --database-db-name=bigcluster
...
/go-ycsb run mysql -P /workloads/betting -p recordcount=200000000 -p dbnameprefix=betting_ -p tablecount=2000 -p unitnameprefix=unit2_ -p databaseproportions=1.0 -p unitscount=20 -p operationcount=9223362036854775807 -p mysql.host=upstream-tidb.cdc-kafka-avro-2-workloads-tps-1830435-1-922 -p mysql.port=4000 --threads=32
```

### What did you expect?
TiKV should not OOM

### What did happened?
TiKV OOM seen after running workload

![image](https://github.com/tikv/tikv/assets/7403864/682b8ced-d407-41e0-80bf-9509967d954c)

![image](https://github.com/tikv/tikv/assets/7403864/a00245e7-e752-47ff-b87a-837ebff12c28)

**Comment by fubinzh** [comment]
Retested this scenario 8C 32GB TiKV, TiKV OOM is still seen (TiKV memory usage upto ~42GB per the metrics), and cdc changefeed stucks.

![image](https://github.com/tikv/tikv/assets/7403864/52a060de-eea9-4776-be88-8a5090e56364)
![image](https://github.com/tikv/tikv/assets/7403864/088b21e6-87fd-4497-87de-c99d5c5eee4c)
![image](https://github.com/tikv/tikv/assets/7403864/497eeb07-b86b-46f5-913f-fb86a5006aa1)


TiKV configuration
```
tikv:
          baseImage: hub-new.pingcap.net/qa/tikv
          config: |
            storage.engine = "partitioned-raft-kv"
          limits:
            cpu: 8000m
            memory: 32Gi
            storage: 3000Gi
          maxReplicas: 3
          replicas: 3
          requests:
            cpu: 8000m
            memory: 32Gi
            storage: 3000Gi
          storageClassName: fast-disks
          version: master
```
