### ISSUE TITLE
[Dynamic Regions] Auto Analyze failed for context deadline exceeded

### ISSUE THREAD

**Issue by lilinghai** [tikv/tikv#15575]
### What operating system and CPU are you using?

Release Version:   7.4.0-alpha
Edition:           Community
Git Commit Hash:   87d0f7cf143524222b4b0d80a4a8c5e02d11cf67
Git Commit Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time:    2023-09-07 11:47:00
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
### Steps to reproduce

The cluster contains about 60 tikv with dynamic region enabled, each tikv contains 2.5TB data, a table contains about 6billion rows with each row size about 10kb.
auto analyze always failed for wait recvLoop: context deadline exceeded
```
mysql> show analyze status \G
*************************** 1. row ***************************
        Table_schema: xxx
          Table_name: t1
      Partition_name:
            Job_info: auto analyze table all columns with 256 buckets, 500 topn, 6.058293454781894e-05 samplerate
      Processed_rows: 41324846
          Start_time: 2023-09-12 17:06:54
            End_time: NULL
               State: running
         Fail_reason: NULL
            Instance: tc-tidb-4.tc-tidb-peer.partition-raft-s9dkz.svc:4000
          Process_ID: 1917548278841343
   Remaining_seconds: -279h36m27s
            Progress: 0.02276134057120847
Estimated_total_rows: 1815571709
*************************** 2. row ***************************
        Table_schema: xxx
          Table_name: t1
      Partition_name:
            Job_info: auto analyze table all columns with 256 buckets, 500 topn, 6.058174326120741e-05 samplerate
      Processed_rows: 107188153
          Start_time: 2023-09-12 14:38:40
            End_time: 2023-09-12 17:06:54
               State: failed
         Fail_reason: wait recvLoop: context deadline exceeded
            Instance: tc-tidb-4.tc-tidb-peer.partition-raft-s9dkz.svc:4000
          Process_ID: NULL
   Remaining_seconds: NULL
            Progress: NULL
Estimated_total_rows: NULL
*************************** 3. row ***************************
        Table_schema: xxx
          Table_name: t1
      Partition_name:
            Job_info: auto analyze table all columns with 256 buckets, 500 topn, 6.058174329457239e-05 samplerate
      Processed_rows: 107188157
          Start_time: 2023-09-12 12:37:35
            End_time: 2023-09-12 14:38:40
               State: failed
         Fail_reason: wait recvLoop: context deadline exceeded
            Instance: tc-tidb-4.tc-tidb-peer.partition-raft-s9dkz.svc:4000
          Process_ID: NULL
   Remaining_seconds: NULL
            Progress: NULL
Estimated_total_rows: NULL
```
