### ISSUE TITLE
Can't set raft-engine.dir as the same as raftstore.raftdb-path when upgrading

### ISSUE THREAD

**Issue by Smityz** [tikv/tikv#15771]
### What version of TiKV are you using?

```
$ ./bin/tikv-server --version
TiKV
Release Version:   6.5.3
Edition:           Community
Git Commit Hash:   fd5f88a7fdda1bf70dcb0d239f60137110c54d46
Git Commit Branch: heads/refs/tags/v6.5.3
UTC Build Time:    2023-06-09 10:55:15
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
```

### Steps to reproduce

1. Deploy a low version TiKV which uses raftdb, and set raftstore.raftdb-path
```
- host: x.x.x.x
  ssh_port: 22
  port: 43000
  status_port: 43001
  deploy_dir: x
  data_dir: x
  log_dir: x
  config:
    raftstore.raftdb-path: /old-raftdb-dir
```
2. Upgrade TiKV with TiUP to v6.5.3
3. The origin `raftstore.raftdb-path` is clear, but the `raft-engine.dir` is set the default value

### What did you expect?
`raft-engine.dir` should be set as the same dir as  `raftstore.raftdb-path`
