### ISSUE TITLE
Slow message handling: `CompactedEvent(RocksCompactedEvent)` takes 3ms

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#18532]
## Development Task

```log
[2025/06/11 02:25:37.449 +00:00] [WARN] [store.rs:923] ["dbg slow store message handling"] [elapsed=3.518013ms] [msg="CompactedEvent(RocksCompactedEvent { cf: \"write\", output_level: 4, total_input_bytes: 3932552, total_output_bytes: 3333753, start_key: [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 130, 95, 114, 128, 0, 0, 0, 1, 255, 183, 10, 203, 0, 0, 0, 0, 0, 250, 249, 162, 147, 254, 133, 195, 255, 246], end_key: [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 131, 95, 114, 128, 0, 0, 0, 0, 255, 159, 10, 129, 0, 0, 0, 0, 0, 250, 249, 162, 156, 65, 140, 159, 254, 188], input_props: [RangeProperties { offsets: [([122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 130, 95, 114, 128, 0, 0, 0, 1, 255, 183, 10, 203, 0, 0, 0, 0, 0, 250, 249, 162, 147, 254, 133, 195, 255, 246], RangeOffsets { size: 245, keys: 1 }), ([122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 131, 95, 114, 128, 0, 0, 0, 0, 255, 159, 10, 129, 0, 0, 0, 0, 0, 250, 249, 162, 156, 65, 140, 159, 254, 188], RangeOffsets { size: 1016750, keys: 4150 })] }, RangeProperties { offsets: [([122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 130, 95, 114, 128, 0, 0, 0, 4, 255, 142, 219, 239, 0, 0, 0, 0, 0, 250, 249, 162, 210, 38, 58, 163, 255, 213], RangeOffsets { size: 245, keys: 1 }), ([122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 130, 95, 114, 128, 0, 0, 0, 4, 255, 142, 231, 220, 0, 0, 0, 0, 0, 250, 249, 162, 210, 38, 14, 227, 255, 100], RangeOffsets { size: 748230, keys: 3054 })] }, RangeProperties { offsets: [([122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 130, 95, 114, 128, 0, 0, 0, 1, 255, 199, 52, 117, 0, 0, 0, 0, 0, 250, 249, 162, 212, 233, 48, 167, 255, 254], RangeOffsets { size: 245, keys: 1 }), ([122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 130, 95, 114, 128, 0, 0, 0, 4, 255, 142, 219, 238, 0, 0, 0, 0, 0, 250, 249, 162, 210, 38, 58, 163, 255, 213], RangeOffsets { size: 2181970, keys: 8906 })] }], output_props: [RangeProperties { offsets: [([122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 131, 95, 114, 128, 0, 0, 0, 0, 255, 87, 118, 158, 0, 0, 0, 0, 0, 250, 249, 162, 156, 126, 254, 79, 255, 193], RangeOffsets { size: 245, keys: 1 }), ([122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 131, 95, 114, 128, 0, 0, 0, 0, 255, 159, 10, 129, 0, 0, 0, 0, 0, 250, 249, 162, 156, 65, 140, 159, 254, 188], RangeOffsets { size: 250880, keys: 1024 })] }, RangeProperties { offsets: [([122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 130, 95, 114, 128, 0, 0, 0, 1, 255, 183, 10, 203, 0, 0, 0, 0, 0, 250, 249, 162, 147, 254, 133, 195, 255, 246], RangeOffsets { size: 245, keys: 1 }), ([122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 130, 95, 114, 128, 0, 0, 0, 1, 255, 199, 89, 168, 0, 0, 0, 0, 0, 250, 249, 162, 148, 89, 97, 35, 254, 169], RangeOffsets { size: 1275225, keys: 5205 })] }, RangeProperties { offsets: [([122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 130, 95, 114, 128, 0, 0, 0, 1, 255, 199, 95, 144, 0, 0, 0, 0, 0, 250, 249, 162, 149, 79, 175, 11, 254, 225], RangeOffsets { size: 245, keys: 1 }), ([122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 130, 95, 114, 128, 0, 0, 0, 4, 255, 142, 231, 220, 0, 0, 0, 0, 0, 250, 249, 162, 210, 38, 14, 227, 255, 100], RangeOffsets { size: 2420845, keys: 9881 })] }] })"] [thread_id=105]
```

The log is taken from a TiKV instance that runs 238k peers and manages 231k sst files.

<img width="2275" alt="Image" src="https://github.com/user-attachments/assets/49cb272a-b88c-4999-924e-c5caf856b668" />

<details><summary>Cluster Details</summary>
<p>

The TiKV is built from https://github.com/overvenus/tikv/tree/log-slow-message

TiKV configuration:

```toml
      [coprocessor]
        region-split-size = "2MiB"

      [log]
        [log.file]
          filename = "/var/lib/tikv/log/tikv.log"
          max-backups = 100
          max-size = 300

      [rocksdb]
        max-manifest-file-size = "256MiB"
        [rocksdb.defaultcf]
          compaction-guard-max-output-file-size = "2MiB"
          compaction-guard-min-output-file-size = "1MiB"
          target-file-size-base = "1MiB"
        [rocksdb.writecf]
          compaction-guard-max-output-file-size = "2MiB"
          compaction-guard-min-output-file-size = "1MiB"
          target-file-size-base = "1MiB"

      [server]
        snap-min-ingest-size = "2KiB"

      [storage]
        reserve-space = "0MB"
```

Test scripts:

```sh
# Prepare
sysbench --db-driver=mysql --mysql-host=tc-tidb-peer --mysql-port=4000 --mysql-user=root         --mysql-db=sbtest --tables=35 --table-size=40351404 --time=3600 --report-interval=3 --threads=20 --auto_inc=true         --create_secondary=off --non_index_updates=10 --mysql-ignore-errors=1105 oltp_update_non_index prepare

# Run
sysbench --db-driver=mysql --mysql-host=tc-tidb-peer --mysql-port=4000 --mysql-user=root         --mysql-db=sbtest --tables=35 --table-size=40351404 --time=3600 --report-interval=3 --threads=200 --auto_inc=true         --create_secondary=off --non_index_updates=10 --mysql-ignore-errors=1105 oltp_update_non_index run
```

</p>
</details>
