### ISSUE TITLE
Slow message handling: `AwakenRegions` takes 390ms

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#18533]
## Development Task

```log
[2025/06/11 02:33:45.594 +00:00] [INFO] [pd.rs:1462] ["forcely awaken hibernated regions in this store"] [thread_id=34]
[2025/06/11 02:33:45.595 +00:00] [INFO] [store.rs:2899] ["try to wake up all hibernated regions in this store"] [to_all=false] [thread_id=105]
[2025/06/11 02:33:45.985 +00:00] [WARN] [store.rs:923] ["dbg slow store message handling"] [elapsed=390.595831ms] [msg="AwakenRegions { abnormal_stores: [1] }"] [thread_id=105]
```

The log is taken from a TiKV instance that runs 238k peers and manages 231k sst files.

<img width="2275" alt="Image" src="https://github.com/user-attachments/assets/49cb272a-b88c-4999-924e-c5caf856b668" />

<img width="2274" alt="Image" src="https://github.com/user-attachments/assets/19b19aef-9043-4964-b8cf-21447db47b99" />

<details><summary>Cluster Details</summary>
<p>

The TiKV is built from https://github.com/overvenus/tikv/tree/log-slow-message

TiKV configuration:

```toml
      [coprocessor]
        region-split-size = "2MiB"

      [log]
        [log.file]
          filename = "/var/lib/tikv/log/tikv.log"
          max-backups = 100
          max-size = 300

      [rocksdb]
        max-manifest-file-size = "256MiB"
        [rocksdb.defaultcf]
          compaction-guard-max-output-file-size = "2MiB"
          compaction-guard-min-output-file-size = "1MiB"
          target-file-size-base = "1MiB"
        [rocksdb.writecf]
          compaction-guard-max-output-file-size = "2MiB"
          compaction-guard-min-output-file-size = "1MiB"
          target-file-size-base = "1MiB"

      [server]
        snap-min-ingest-size = "2KiB"

      [storage]
        reserve-space = "0MB"
```

Test scripts:

```sh
# Prepare
sysbench --db-driver=mysql --mysql-host=tc-tidb-peer --mysql-port=4000 --mysql-user=root         --mysql-db=sbtest --tables=35 --table-size=40351404 --time=3600 --report-interval=3 --threads=20 --auto_inc=true         --create_secondary=off --non_index_updates=10 --mysql-ignore-errors=1105 oltp_update_non_index prepare

# Run
sysbench --db-driver=mysql --mysql-host=tc-tidb-peer --mysql-port=4000 --mysql-user=root         --mysql-db=sbtest --tables=35 --table-size=40351404 --time=3600 --report-interval=3 --threads=200 --auto_inc=true         --create_secondary=off --non_index_updates=10 --mysql-ignore-errors=1105 oltp_update_non_index run
```

</p>
</details>
