### ISSUE TITLE
tikv_coprocessor_request_error,reason="stale_epoch", value = 344

### ISSUE THREAD

**Issue by denghuancong** [tikv/tikv#3611]
base info
tidb version: v2.0.4
-------------------------
we receive some warning message from prometheus， that we setup for out tidb cluster。
```
{instance="8f63abd463b7",job="bac2b3c9-fe3f-4c77-a492-d69718e63b1a_5",reason="stale_epoch"}
value is 344
```
the stale_epoch count is 344 , we checkout the alert config:
```
- alert: TiKV_coprocessor_request_error
    expr: increase(tikv_coprocessor_request_error[10m]) > 100
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      severity: warning
      expr:  increase(tikv_coprocessor_request_error[10m]) > 100
    annotations:
      description: 'cluster: ENV_LABELS_ENV, type: {{ $labels.type }}, instance: {{ $labels.instance }}, values: {{ $value }}'
      value: '{{ $value }}'
      summary: TiKV coprocessor_request_error
```
It match the alert rule.  The background is we are importting data, I google it , it seem that the tikv region matter, what is this warning acturally mee?
