### ISSUE TITLE
TiKV insert tune

### ISSUE THREAD

**Issue by Guhaiyan** [tikv/tikv#3826]
What I want to know is
1. what is the bottleneck?
2. Commonly, what I need to pay attention to among so many graphs?
3. Also, several hundred parameters in tikv.yml, any detailed tuning guide?

Below is test related info provided.
Env:
Linux version 3.10.0-693.el7.x86_64 (builder@kbuilder.dev.centos.org)
three nodes with 128G mem , HDD

Tools: go-ycsb

workload and result
***************** properties *****************
"measurementtype"="timeseries"
"operationcount"="10000000"
"workload"="core"
"updateproportion"="0.5"
"insertproportion"="0"
"scanproportion"="0"
"threadcount"="200"
"readallfields"="true"
"timeseries.granularity"="1000"
"dotransactions"="false"
"requestdistribution"="zipfian"
"readproportion"="0.5"
"insertorder"="hashed"
"recordcount"="10000000"
"tikv.pd"="xxx.xxx.xxx.xxx:2379"
**********************************************
INSERT - Takes(s): 10.0, Count: 472177, OPS: 47412.4, Avg(us): 4154, Min(us): 721, Max(us): 158564, 95th(us): 7000, 99th(us): 29000
INSERT - Takes(s): 20.0, Count: 831212, OPS: 41646.1, Avg(us): 4731, Min(us): 721, Max(us): 279654, 95th(us): 8000, 99th(us): 47000
INSERT - Takes(s): 30.0, Count: 1223112, OPS: 40826.3, Avg(us): 4825, Min(us): 721, Max(us): 279654, 95th(us): 10000, 99th(us): 47000
INSERT - Takes(s): 40.0, Count: 1656567, OPS: 41456.6, Avg(us): 4746, Min(us): 721, Max(us): 279654, 95th(us): 10000, 99th(us): 43000
INSERT - Takes(s): 50.0, Count: 2029651, OPS: 40626.3, Avg(us): 4848, Min(us): 721, Max(us): 279654, 95th(us): 9000, 99th(us): 54000
INSERT - Takes(s): 60.0, Count: 2417466, OPS: 40318.7, Avg(us): 4885, Min(us): 721, Max(us): 1708979, 95th(us): 8000, 99th(us): 52000
INSERT - Takes(s): 70.0, Count: 2794572, OPS: 39945.3, Avg(us): 4931, Min(us): 721, Max(us): 1708979, 95th(us): 8000, 99th(us): 56000
INSERT - Takes(s): 80.0, Count: 3175700, OPS: 39716.6, Avg(us): 4960, Min(us): 718, Max(us): 1708979, 95th(us): 8000, 99th(us): 56000
INSERT - Takes(s): 90.0, Count: 3418412, OPS: 37999.5, Avg(us): 5187, Min(us): 718, Max(us): 1708979, 95th(us): 9000, 99th(us): 63000
INSERT - Takes(s): 100.0, Count: 3740878, OPS: 37424.2, Avg(us): 5268, Min(us): 718, Max(us): 1708979, 95th(us): 10000, 99th(us): 62000
INSERT - Takes(s): 110.0, Count: 4089178, OPS: 37188.2, Avg(us): 5302, Min(us): 718, Max(us): 1708979, 95th(us): 11000, 99th(us): 62000
INSERT - Takes(s): 120.0, Count: 4202729, OPS: 35034.7, Avg(us): 5631, Min(us): 718, Max(us): 1708979, 95th(us): 12000, 99th(us): 76000
INSERT - Takes(s): 130.0, Count: 4413228, OPS: 33958.6, Avg(us): 5812, Min(us): 718, Max(us): 1708979, 95th(us): 12000, 99th(us): 79000
INSERT - Takes(s): 140.0, Count: 4770619, OPS: 34085.9, Avg(us): 5792, Min(us): 718, Max(us): 1708979, 95th(us): 12000, 99th(us): 80000
INSERT - Takes(s): 150.0, Count: 4967294, OPS: 33124.3, Avg(us): 5960, Min(us): 718, Max(us): 1708979, 95th(us): 12000, 99th(us): 85000
INSERT - Takes(s): 160.0, Count: 5184751, OPS: 32412.7, Avg(us): 6096, Min(us): 718, Max(us): 1708979, 95th(us): 12000, 99th(us): 88000
INSERT - Takes(s): 170.0, Count: 5524168, OPS: 32503.0, Avg(us): 6079, Min(us): 718, Max(us): 1708979, 95th(us): 12000, 99th(us): 87000
INSERT - Takes(s): 180.0, Count: 5804294, OPS: 32253.4, Avg(us): 6126, Min(us): 718, Max(us): 1708979, 95th(us): 13000, 99th(us): 87000
INSERT - Takes(s): 190.0, Count: 6112980, OPS: 32180.5, Avg(us): 6140, Min(us): 718, Max(us): 1708979, 95th(us): 12000, 99th(us): 87000
INSERT - Takes(s): 200.0, Count: 6348800, OPS: 31750.5, Avg(us): 6223, Min(us): 718, Max(us): 1708979, 95th(us): 13000, 99th(us): 88000
INSERT - Takes(s): 210.0, Count: 6621611, OPS: 31537.6, Avg(us): 6268, Min(us): 718, Max(us): 1708979, 95th(us): 13000, 99th(us): 89000
INSERT - Takes(s): 220.0, Count: 6906313, OPS: 31398.2, Avg(us): 6295, Min(us): 718, Max(us): 1708979, 95th(us): 13000, 99th(us): 89000
INSERT - Takes(s): 230.0, Count: 7252269, OPS: 31537.0, Avg(us): 6268, Min(us): 718, Max(us): 1708979, 95th(us): 12000, 99th(us): 88000
INSERT - Takes(s): 240.0, Count: 7522130, OPS: 31347.6, Avg(us): 6305, Min(us): 718, Max(us): 1708979, 95th(us): 12000, 99th(us): 89000
INSERT - Takes(s): 250.0, Count: 7816524, OPS: 31271.2, Avg(us): 6322, Min(us): 718, Max(us): 1708979, 95th(us): 12000, 99th(us): 89000
INSERT - Takes(s): 260.0, Count: 8159050, OPS: 31385.9, Avg(us): 6299, Min(us): 718, Max(us): 1708979, 95th(us): 12000, 99th(us): 89000
INSERT - Takes(s): 270.0, Count: 8417663, OPS: 31181.3, Avg(us): 6339, Min(us): 718, Max(us): 1708979, 95th(us): 12000, 99th(us): 89000
INSERT - Takes(s): 280.0, Count: 8732798, OPS: 31193.1, Avg(us): 6339, Min(us): 718, Max(us): 1708979, 95th(us): 12000, 99th(us): 89000
INSERT - Takes(s): 290.0, Count: 9078187, OPS: 31308.5, Avg(us): 6315, Min(us): 718, Max(us): 1708979, 95th(us): 12000, 99th(us): 88000
INSERT - Takes(s): 300.0, Count: 9325760, OPS: 31090.1, Avg(us): 6360, Min(us): 718, Max(us): 1708979, 95th(us): 12000, 99th(us): 89000
INSERT - Takes(s): 310.0, Count: 9654379, OPS: 31147.3, Avg(us): 6347, Min(us): 718, Max(us): 1708979, 95th(us): 11000, 99th(us): 89000
INSERT - Takes(s): 320.0, Count: 9929018, OPS: 31032.2, Avg(us): 6372, Min(us): 718, Max(us): 1708979, 95th(us): 11000, 99th(us): 89000
Run finished, takes 5m22.640811609s
INSERT - Takes(s): 322.6, Count: 10000000, OPS: 30998.8, Avg(us): 6370, Min(us): 648, Max(us): 1708979, 95th(us): 11000, 99th(us): 89000

tikv.toml
```toml
log-level = "error"

[readpool.storage]

[readpool.coprocessor]

[server]
grpc-concurrency = 16
grpc-raft-conn-num = 32
labels = {  }

[storage]
scheduler-concurrency = 2048000
scheduler-worker-pool-size = 16

[pd]
# This section will be overwritten by command line parameters

[metric]
address = "10.10.12.11:9091"
interval = "15s"
job = "tikv"

[raftstore]
raft-log-gc-size-limit = "384MB"
raftdb-path = ""
region-split-check-diff = "512MB"
sync-log = true

[coprocessor]
region-max-size = "684MB"
region-split-size = "512MB"

[rocksdb]
enable-statistics = true
max-background-jobs = 16
max-open-files = 65535
use-direct-io-for-flush-and-compaction = false
wal-dir = ""

[rocksdb.defaultcf]
block-cache-size = "13GB"
level0-file-num-compaction-trigger = 8
level0-slowdown-writes-trigger = 24
level0-stop-writes-trigger = 48
max-bytes-for-level-base = "1GB"
max-write-buffer-number = 10
target-file-size-base = "64MB"
write-buffer-size = "128MB"

[rocksdb.lockcf]
block-cache-size = "2GB"
write-buffer-size = "128MB"

[rocksdb.writecf]
block-cache-size = "6GB"
write-buffer-size = "128MB"

[raftdb]
compaction-readahead-size = "6M"

[raftdb.defaultcf]
block-cache-size = "1GB"
write-buffer-size = "128MB"

[security]
ca-path = ""
cert-path = ""
key-path = ""

[import]
```
Graph report by Grafana is attached.
[test-cluster-tikv.pdf](https://github.com/tikv/tikv/files/2610790/test-cluster-tikv.pdf)
