### ISSUE TITLE
Why is reading very slow?

### ISSUE THREAD

**Issue by lqxn1015** [tikv/tikv#3869]
I found a problem when using tikv. read very slowly. 

this is my tikv config 

```toml
log-level = "info"
log-file = "/data01/tikv/logs/tikv.log"

[server]
addr = "192.168.200.81:20160"


[storage]
data-dir = "/data01/tikv/data"

[pd]
endpoints = ["192.168.200.81:2379","192.168.200.82:2379","192.168.200.83:2379"]

[metric]
interval = "15s"
address = ""
job = "tikv"

[raftstore]
sync-log = false


region-max-size = "384MB"
region-split-size = "256MB"
region-split-check-diff = "32MB"

[rocksdb]
max-manifest-file-size = "20MB"
wal-dir = "/data01/tikv/data"

[rocksdb.defaultcf]
block-size = "64KB"
compression-per-level = ["no", "no", "lz4", "lz4", "lz4", "zstd", "zstd"]

write-buffer-size = "128MB"

max-write-buffer-number = 5

level0-slowdown-writes-trigger = 20

level0-stop-writes-trigger = 36

max-bytes-for-level-base = "512MB"

target-file-size-base = "32MB"


[rocksdb.writecf]
compression-per-level = ["no", "no", "lz4", "lz4", "lz4", "zstd", "zstd"]

write-buffer-size = "128MB"
max-write-buffer-number = 5
min-write-buffer-number-to-merge = 1

max-bytes-for-level-base = "512MB"
target-file-size-base = "32MB"

[raftdb]
compaction-readahead-size = "2MB"

[raftdb.defaultcf]
compression-per-level = ["no", "no", "lz4", "lz4", "lz4", "zstd", "zstd"]

write-buffer-size = "128MB"
max-write-buffer-number = 5
min-write-buffer-number-to-merge = 1

max-bytes-for-level-base = "512MB"
target-file-size-base = "32MB"

block-cache-size = "256MB"
```

and  this is pd server

/data01/tidb-latest-linux-amd64/bin/pd-server --name=pd1 \ --data-dir=/data01/pdserver/data \ --client-urls="http://192.168.200.81:2379" \ --peer-urls="http://192.168.200.81:2380" \ --initial-cluster="pd1=http://192.168.200.81:2380,pd2=http://192.168.200.82:2380,pd3=http://192.168.200.83:2380" \ -L "info" \ --log-file=/data01/pdserver/logs/pd.log

use 20 go goroutines and chan send 1000000 key read  need  about 12 minutes  .

In the same situation  20 go goroutines and chan send 1000000 key  value  , writing only takes 1 minute.

reading  
![image](https://user-images.githubusercontent.com/4476386/49361218-645da500-f716-11e8-815a-51e47515a24c.png)

what is causing this problem?

thank you .
