### ISSUE TITLE
TiKV consumes too many memories, almost double of the sum of block cache size

### ISSUE THREAD

**Issue by lerencao** [tikv/tikv#4120]
## Bug Report

**What version of Rust are you using?**

`Rust Version:      rustc 1.29.0-nightly (4f3c7a472 2018-07-17)`

**What operating system and CPU are you using?**
CentOS 

```
processor       : 39
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
```

**What did you do?**

A TiKV node consume 50G mems, while block cache is 14G + 10G + 2G + 2G + others ~= 30G, more or less.

custom config is: 

```
raftstore:
  capacity: "600GB"
  notify-capacity: 81920
  messages-per-tick: 6144
rocksdb:
  max-background-jobs: 6
  max-sub-compactions: 2
  defaultcf:
    level0-slowdown-writes-trigger: 192
    level0-stop-writes-trigger: 288
    max-compaction-bytes: "1GB"
    block-cache-size: "14GB"
  writecf:
    level0-slowdown-writes-trigger: 192
    level0-stop-writes-trigger: 288
    max-compaction-bytes: "1GB"
    block-cache-size: "10GB"
  lockcf:
    level0-slowdown-writes-trigger: 72
    level0-stop-writes-trigger: 96
    block-cache-size: "2GB"
raftdb:
  defaultcf:
    block-cache-size: "2GB"
```

I wonder if it's normal for other parts consuming 20G memories more.

![image](https://user-images.githubusercontent.com/1456096/51721484-f46ff900-208c-11e9-81f2-6199069bf7b6.png)

The mem of TiKV increased in `01-23` and `01-24`.

Corresponding block cache:

![image](https://user-images.githubusercontent.com/1456096/51721586-7102d780-208d-11e9-8baf-f923681ef5a1.png)

**What did you expect to see?**

**What did you see instead?**
