### ISSUE TITLE
RotatingFileLoggerPanics on drop

### ISSUE THREAD

**Issue by brson** [tikv/tikv#4312]
It's not ok generally to panic in destructors because of the risk of double-panic ([see api guide](https://rust-lang-nursery.github.io/api-guidelines/dependability.html#destructors-never-fail-c-dtor-fail)), which causes an abort.

RotatingFileLogger's drop method calls `close` which calls `flush` on a file, which can fail. It then unwraps that result, potentially panicking. The best that con be done by the time the dtor is called is to silently ignore the failed call to `close` and hope for the best.

**Comment by brson** [comment]
Before trying to fix this I think we should get more clarity on the downsides of using `thread::panicking` in drop.

**Comment by axelmagn** [comment]
I am interested in patching this.  I think I've got a handle on how I would do it.  I did some googling, but I couldn't find any reference to the downsides of thread::panicking that you are referring to.

**Comment by brson** [comment]
@axelmagn great, please give it a try.

I chatted a bit on #rust-libs about fallible destructor patterns today, and came away thinking we should go ahead and use thread::panicking to avoid the double-panic.

Generally though, I think the best pattern for fallible destructors is to have a close method that returns a Result, and a drop method that verifies that close was called. I sketched out how this looks [here](https://gist.github.com/brson/4ab0526baab38972bccdfb60ef7a9bd9), though I must say I've never seen code with the dual `close()`/`destroy()` methods like this.

**Comment by brson** [comment]
@axelmagn if you like this one, there are two more like it: https://github.com/tikv/tikv/issues/4310, https://github.com/tikv/tikv/issues/4309

**Comment by liufuyang** [comment]
@axelmagn Are you still working on this? Or is there something I can also help with?

**Comment by kennytm** [comment]
There's an easy way to reproduce the double panic crash.

1. Start TiKV, log to some folder, and set a very short log rotation period

    ```toml
    log-file = "inaccessible/tikv.log"
    log-rotation-timespan = "5s"

    [server]
    addr = "127.0.0.1:20160"
    advertise-addr = "127.0.0.1:20160"

    [pd]
    endpoints = ["127.0.0.1:2379"]

    [rocksdb]
    max-open-files = 4096

    [raftdb]
    max-open-files = 4096
    ```

    ```sh
    mkdir inaccessible
    target/debug/tikv-server -C config.toml
    ```

2. Make the log folder read-only (*in practice, this means any kind of I/O error happening during log rotation*)

    ```sh
    chmod a-w inaccessible
    ```

3. Force TiKV to log something, e.g. send SIGUSR1 to it.

    ```sh
    kill -USR1 7096
    ```

4. TiKV will now crash with the pretty obscure error `[FATAL] [mod.rs:484] ["failed to join thread: Resource deadlock avoided (os error 35)"]`, while the original error causing the double panic is lost.
