### ISSUE TITLE
Use docker-compose to deploy a TiKV cluster in a single machine, no replication happens.

### ISSUE THREAD

**Issue by Yriuns** [tikv/tikv#4816]
## Bug Report

**What version of TiKV are you using?**
```
TiKV
Release Version:   3.0.0-beta.1
Git Commit Hash:   85bb786ea4f4ee66db04f4bb252d590dcf804d7d
Git Commit Branch: master
UTC Build Time:    2019-05-30 02:31:14
Rust Version:      rustc 1.36.0-nightly (e305df184 2019-04-24)
```

**What operating system and CPU are you using?**
```
Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-145-generic x86_64)
```

**What did you do?**

1.  Use `docker-compose ` to start 3 `TiKV` and `PD` in 1 machine

```
version: "3"
services:
  pd0:
    image: pingcap/pd:latest
    ports:
      - "2379"
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380,pd1=http://pd1:2380,pd2=http://pd2:2380
      - --data-dir=/data/pd0
      - --log-file=/logs/pd0.log
    restart: on-failure
  pd1:
    image: pingcap/pd:latest
    ports:
      - "2379"
    command:
      - --name=pd1
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd1:2379
      - --advertise-peer-urls=http://pd1:2380
      - --initial-cluster=pd0=http://pd0:2380,pd1=http://pd1:2380,pd2=http://pd2:2380
      - --data-dir=/data/pd1
      - --log-file=/logs/pd1.log
    restart: on-failure
  pd2:
    image: pingcap/pd:latest
    ports:
      - "2379"
    command:
      - --name=pd2
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd2:2379
      - --advertise-peer-urls=http://pd2:2380
      - --initial-cluster=pd0=http://pd0:2380,pd1=http://pd1:2380,pd2=http://pd2:2380
      - --data-dir=/data/pd2
      - --log-file=/logs/pd2.log
    restart: on-failure

  tikv0:
    image: pingcap/tikv:latest
    ports:
      - "20160"
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv0:20160
      - --data-dir=/data/tikv0
      - --pd=pd0:2379,pd1:2379,pd2:2379
      - --log-file=/logs/tikv0.log
    depends_on:
      - "pd0"
    restart: on-failure
  tikv1:
    image: pingcap/tikv:latest
    ports:
      - "20160"
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv1:20160
      - --data-dir=/data/tikv1
      - --pd=pd0:2379,pd1:2379,pd2:2379
      - --log-file=/logs/tikv1.log
    depends_on:
      - "pd0"
    restart: on-failure
  tikv2:
    image: pingcap/tikv:latest
    ports:
      - "20160"
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv2:20160
      - --data-dir=/data/tikv2
      - --pd=pd0:2379,pd1:2379,pd2:2379
      - --log-file=/logs/tikv2.log
    depends_on:
      - "pd0"
    restart: on-failure
```

the `pd-ctl` shows the cluster is healthy, and the number of replica is 3

```
» health
[
  {
    "name": "pd0",
    "member_id": 2569432990168970607,
    "client_urls": [
      "http://pd0:2379"
    ],
    "health": true
  },
  {
    "name": "pd1",
    "member_id": 5121893302248312363,
    "client_urls": [
      "http://pd1:2379"
    ],
    "health": true
  },
  {
    "name": "pd2",
    "member_id": 6077736303471108965,
    "client_urls": [
      "http://pd2:2379"
    ],
    "health": true
  }
]
```
```
» config show all
{
  "client-urls": "http://0.0.0.0:2379",
  "peer-urls": "http://0.0.0.0:2380",
  "advertise-client-urls": "http://pd0:2379",
  "advertise-peer-urls": "http://pd0:2380",
  "name": "pd0",
  "data-dir": "/data/pd0",
  "force-new-cluster": false,
  "initial-cluster": "pd0=http://pd0:2380,pd1=http://pd1:2380,pd2=http://pd2:2380",
  "initial-cluster-state": "new",
  "join": "",
  "lease": 3,
  "log": {
    "level": "",
    "format": "text",
    "disable-timestamp": false,
    "file": {
      "filename": "/logs/pd0.log",
      "log-rotate": true,
      "max-size": 300,
      "max-days": 0,
      "max-backups": 0
    },
    "development": false,
    "disable-caller": false,
    "disable-stacktrace": false,
    "sampling": null
  },
  "log-file": "",
  "log-level": "",
  "tso-save-interval": "3s",
  "metric": {
    "job": "pd0",
    "address": "",
    "interval": "15s"
  },
  "schedule": {
    "max-snapshot-count": 3,
    "max-pending-peer-count": 16,
    "max-merge-region-size": 20,
    "max-merge-region-keys": 200000,
    "split-merge-interval": "1h0m0s",
    "patrol-region-interval": "100ms",
    "max-store-down-time": "30m0s",
    "leader-schedule-limit": 4,
    "region-schedule-limit": 4,
    "replica-schedule-limit": 8,
    "merge-schedule-limit": 8,
    "hot-region-schedule-limit": 2,
    "hot-region-cache-hits-threshold": 3,
    "tolerant-size-ratio": 5,
    "low-space-ratio": 0.8,
    "high-space-ratio": 0.6,
    "disable-raft-learner": "false",
    "disable-remove-down-replica": "false",
    "disable-replace-offline-replica": "false",
    "disable-make-up-replica": "false",
    "disable-remove-extra-replica": "false",
    "disable-location-replacement": "false",
    "disable-namespace-relocation": "false",
    "schedulers-v2": [
      {
        "type": "balance-region",
        "args": null,
        "disable": false
      },
      {
        "type": "balance-leader",
        "args": null,
        "disable": false
      },
      {
        "type": "hot-region",
        "args": null,
        "disable": false
      },
      {
        "type": "label",
        "args": null,
        "disable": false
      }
    ]
  },
  "replication": {
    "max-replicas": 3,
    "location-labels": ""
  },
  "namespace": {},
  "pd-server": {
    "use-region-storage": "true"
  },
  "cluster-version": "3.0.0-beta.1",
  "quota-backend-bytes": "0 B",
  "auto-compaction-mode": "periodic",
  "auto-compaction-retention-v2": "1h",
  "TickInterval": "500ms",
  "ElectionInterval": "3s",
  "PreVote": true,
  "security": {
    "cacert-path": "",
    "cert-path": "",
    "key-path": ""
  },
  "label-property": {},
  "WarningMsgs": null,
  "namespace-classifier": "table",
  "LeaderPriorityCheckInterval": "1m0s"
}
```

2. put some `key-value`

**What did you expect to see?**
each region has 3 peers
**What did you see instead?**
each region has only one peer
```
    {
      "id": 168,
      "start_key": "7410E41D33ED6B4FFFDA00000000000000F8",
      "end_key": "7411140FAB366F2AFF6C00000000000000F8",
      "epoch": {
        "conf_ver": 1,
        "version": 78
      },
      "peers": [
        {
          "id": 169,
          "store_id": 3
        }
      ],
      "leader": {
        "id": 169,
        "store_id": 3
      },
      "written_bytes": 47286853,
      "approximate_size": 1,
      "approximate_keys": 1
    }
```
```
» region check miss-peer
{
  "count": 217,
  "regions": [
    {
      "id": 344,
      "start_key": "7422A77CA0C07156FFC600000000000000F8",
      "end_key": "7422FEE18052D9C5FFCE00000000000000F8",
      "epoch": {
        "conf_ver": 1,
        "version": 166
      },
      "peers": [
        {
          "id": 345,
          "store_id": 3
        }
      ],
      "leader": {
        "id": 345,
        "store_id": 3
      },
      "approximate_size": 1,
      "approximate_keys": 2
    },
    ...
```
