### ISSUE TITLE
TiKV can't connect to pd "validate PD endpoints failed"

### ISSUE THREAD

**Issue by H-ZeX** [tikv/tikv#5443]
### What operating system and CPU are you using?

```
# hzx @ hzx-X542UQR in ~ [23:38:23] 
$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       39 bits physical, 48 bits virtual
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               142
Model name:          Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Stepping:            10
CPU MHz:             800.010
CPU max MHz:         4000.0000
CPU min MHz:         400.0000
BogoMIPS:            3984.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            8192K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

$ uname -a   
Linux hzx-X542UQR 5.0.0-27-generic #28-Ubuntu SMP Tue Aug 20 19:53:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
### Steps to reproduce
In this PR(https://github.com/tikv/tikv/pull/5427), 
this commit(https://github.com/tikv/tikv/pull/5427/commits/f2c7390ddf6d9c9aca9ffc22c4ccddb0823b870a)
the log is (https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_integration-cop-push-down-test/detail/tikv_ghpr_integration-cop-push-down-test/1126/pipeline)
the tikv can not connect to pd, the main err is `validate PD endpoints failed`

I can reproduce this by use 
```
$ ~/program/goland/tidb/bin/tidb-server -V                               
Release Version: v4.0.0-alpha-222-gd5626a918
Git Commit Hash: d5626a918dffe45bdedeb1d6c7c3c7216dfacc91
Git Branch: HEAD
UTC Build Time: 2019-09-10 12:16:05
GoVersion: go version go1.12.6 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

# hzx @ hzx-X542UQR in ~ [23:29:09] 
$ ~/program/goland/pd/bin/pd-server -V  
Release Version: v4.0.0-alpha-54-ge678a1f5
Git Commit Hash: e678a1f5c022fed729fb79397fe02b6c9f54ff4a
Git Branch: HEAD
UTC Build Time:  2019-09-10 12:17:00

tikv is download from (this commit https://github.com/tikv/tikv/pull/5427/commits/f2c7390ddf6d9c9aca9ffc22c4ccddb0823b870a) 's tikv (http://fileserver.pingcap.net/download/builds/pingcap/tikv/pr/f2c7390ddf6d9c9aca9ffc22c4ccddb0823b870a/centos7/tikv-server.tar.gz)
```

the config is
 
```toml
#  tikv's config

log-level = "info"

[server]
# end-point-enable-batch-if-possible = false
## Listening address.
# addr = "127.0.0.1:20161"
# status-addr = ""

[pd]
endpoints = ["127.0.0.1:3379"]

[storage]
data-dir = "/tmp/tikv_no_batch"
```

```toml
#  pd's config

name = "pd"
data-dir = "/tmp/pd_no_batch"
client-urls = "http://127.0.0.1:3379"
# peer-urls = "http://127.0.0.1:3380"

[log]
level = "info"
```
```toml
# tidb's config

port = 4006
store = "tikv"
path = "127.0.0.1:3379"

[log]
level = "info"

# [status]
# report-status = false

```
the test script is 
```sh
#!/bin/env bash

killall -TERM tikv-server
killall -TERM tidb-server
killall -TERM pd-server

set -e

/bin/rm -rf /tmp/tikv_no_batch
/bin/rm -rf /tmp/pd_no_batch
/bin/rm -rf /tmp/pd_no_batch
/bin/rm -rf /tmp/pd_no_batch
/bin/rm -rf /tmp/pd_push_down_no_batch.log
/bin/rm -rf /tmp/tikv_push_down_no_batch.log
/bin/rm -rf /tmp/tidb_push_down_no_batch.log

/home/hzx/program/goland/pd/bin/pd-server -config /home/hzx/program/goland/tidb-test/push_down_func_test/config/push_down_no_batch/pd.toml -log-file /tmp/pd_push_down_no_batch.log &
echo "end start pd"
/home/hzx/Downloads/tikv-bad/tikv-server -C /home/hzx/program/goland/tidb-test/push_down_func_test/config/push_down_no_batch/tikv.toml -f /tmp/tikv_push_down_no_batch.log &
echo "end start tikv, sleep 2s"
sleep 2
echo "end sleep"
/home/hzx/program/goland/tidb/bin/tidb-server -config /home/hzx/program/goland/tidb-test/push_down_func_test/config/push_down_no_batch/tidb.toml -log-file /tmp/tidb_push_down_no_batch.log &
echo "end start tidb"
```

However, If I replace the tikv by
```
$ ~/Downloads/tikv-9b0/bin/tikv-server -V
TiKV 
Release Version:   4.0.0-alpha
Git Commit Hash:   9b0e35d53adb819cfaad8f9299f4e132874f883d
Git Commit Branch: master
UTC Build Time:    2019-09-10 10:10:13
Rust Version:      rustc 1.39.0-nightly (c6e9c76c5 2019-09-04)
```
the newest tikv until 2019.9.10 23:37, all is ok.
