### ISSUE TITLE
TiKV fails to serve after network partition

### ISSUE THREAD

**Issue by YangKeao** [tikv/tikv#6254]
## Bug Report

I have tried to apply network partition on TiKV to test the stability. And found in some situation TiKV will stop to serve.

### 2/2/1 partition

5 TiKV clusters. They are splitted into three group (which has 2/2/1 TiKV). The connection between first and second group are blocked (through iptables). And the third group can connect with the first and second group.

If you can use chaos-operator, it can be represented as below crd:

```yaml
apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: partitiontikv
  namespace: chaos-testing
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - chaos-operator-test-exp6-cat0-tidb-cluster
    labelSelectors:
      "partition": "1"
  direction: both
  target:
    selector:
      namespaces:
        - chaos-operator-test-exp6-cat0-tidb-cluster
      labelSelectors:
        "partition": "2"
    mode: all
  duration: "5m"
  scheduler:
    cron: "@every 7m"
```

It keeps working for several hours. But after nearly 3 hours, QPS falls to zero.

![image9](https://user-images.githubusercontent.com/5244316/70963372-33eb6d80-20c3-11ea-98ba-b12a83715dce.png)

### 3/2 (one way)

5 TiKVs are splitted into two groups. The TCP connection from second group (which has 2 TiKVs) to first groups is blocked which the reverse is allowed. It can be represented as below:

```yaml
apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: partitiontikv
  namespace: chaos-testing
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - chaos-operator-test-exp7-cat0-tidb-cluster
    labelSelectors:
      "partition": "1"
  direction: from
  target:
    selector:
      namespaces:
        - chaos-operator-test-exp7-cat0-tidb-cluster
      labelSelectors:
        "partition": "2"
    mode: all
  duration: "5m"
  scheduler:
    cron: "@every 7m"
```

In the beginning hours, TiKV stops to work sometimes. 

![image12](https://user-images.githubusercontent.com/5244316/70963718-529e3400-20c4-11ea-886d-c8f73a3e88cd.png)

After several hours TiKV stops working forever (QPS falls to zero).

![image1](https://user-images.githubusercontent.com/5244316/70963731-6053b980-20c4-11ea-9ce1-2a8e3bb10f3f.png)

### What version of TiKV are you using?

Master 28d2e

### Steps to reproduce

You can use chaos-operator and schrodinger to simply reproduce these bugs. 

### What did you expect?

I don't know whether these phenomenons are expected (@5kbpers told me they are not!)
