### ISSUE TITLE
Configuration is not fully checked if the unified read pool is partially enabled

### ISSUE THREAD

**Issue by sticnarf** [tikv/tikv#7384]
### What version of TiKV are you using?

Nightly or latest release-4.0.

### What operating system and CPU are you using?

Unrelated.

### Steps to reproduce

The following invalid configuration is not rejected:

```toml
[readpool.storage]
use-unified-pool = false
stack-size = "1MiB"

[readpool.coprocessor]
use-unified-pool = true
```

### What did you expect?

The above configuration is rejected because the minimal stack size is 2MiB.

### What did happened?

TiKV starts.
