### ISSUE TITLE
Question on docker with local compiled tikv

### ISSUE THREAD

**Issue by Yiyiyimu** [tikv/tikv#7778]
### Problems:
I followed [guideline](https://pingcap.com/docs/stable/how-to/get-started/deploy-tidb-from-docker-compose/#customize-the-cluster) to customize the cluster with tikv locally compiled. When I run ```docker-compose -f generated-docker-compose.yml pull```, I come into the following error:
```
Pulling tikv0 (tikv:latest)...
ERROR: pull access denied for tikv, repository does not exist or may require 'docker login': 
    denied: requested access to the resource is denied
```
I do remove the image name in values.yaml and copy compiled tikv-server from github_folder/target/debug to docker_folder/tikv/bin, so I'm not so sure where am I missing.

Also I wonder if I want to contribute to tikv, do I need to use docker to run the whole environment, or just following this [development setting steps](https://github.com/tikv/tikv/blob/master/CONTRIBUTING.md#building-and-setting-up-a-development-workspace) and test only with make.

### Related file info
values.yaml
```
tikv:
  size: 3
  image: 
  # pingcap/tikv:latest

  # If you want to build tikv image from source, leave image empty and specify tikv source directory
  # and its dockerfile name
  buildPath: ./tikv
  dockerfile: Dockerfile
  # when network mode is host, tikv port ranges [port, port+size)
  port: 20160
```

generated-docker-compose.yml
```
  tikv0:
    image: tikv:latest
    build:
      context: ./tikv
      dockerfile: Dockerfile
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv0:20160
      - --data-dir=/data/tikv0
      - --pd=pd0:2379,pd1:2379,pd2:2379
      - --config=/tikv.toml
      - --log-file=/logs/tikv0.log
    depends_on:
      - "pd0"
      - "pd1"
      - "pd2"
    # sysctls:
    #   net.core.somaxconn: 32768
    # ulimits:
    #   nofile:
    #     soft: 1000000
    #     hard: 1000000
    restart: on-failure
```
