### ISSUE TITLE
Status port not binded on the first start when TLS is enabled

### ISSUE THREAD

**Issue by AstroProfundis** [tikv/tikv#8449]
### What version of TiKV are you using?

```
# bin/tikv-server -V
TiKV 
Release Version:   4.0.4
Edition:           Community
Git Commit Hash:   28e3d44b00700137de4fa933066ab83e5f8306cf
Git Commit Branch: release-4.0
UTC Build Time:    2020-07-29 05:58:16
Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)
Enable Features:   jemalloc portable sse protobuf-codec
Profile:           dist_release
```
### What operating system and CPU are you using?

Not related
### Steps to reproduce

Assume the `tikv-server` is deployed on `172.16.5.163`.

1. Starting a tikv server **without** TLS configured and `--status-addr "172.16.5.163:20180"`, everything works normally and the `tikv-server` is listening on `172.16.5.163:20180`.

2. Starting a tikv server with TLS configured (set cert and key in the config file) and `--status-addr "172.16.5.163:20180"`, only the main 20160 port is listened, there is nothing bind on port 20180.

3. Starting a tikv server with TLS configured and `--status-addr "0.0.0.0:20180"`, the `tikv-server` is listening on `0.0.0.0:20180` and working.

4. Starting a tikv server with TLS configured and `--status-addr "0.0.0.0:20180" --advertise-status-addr "172.16.5.163:20180"`, the port 20180 is not listened by anything, same as 2.

All tests are make with `--addr "0.0.0.0:20160" --advertise-addr "172.16.5.163:20160"` set, and the 20160 port is listened and working normally on all 4 tests described above.

I didn't find anything suspicious in the log, no errors about `status_address` nor port `20180`.

### What did you expect?
The status port is binded by tikv server with HTTPS when TLS is configured in the config file and working.

### What did happened?
The port is not bind by tikv when:
1. TLS is configured in config file, and
2. The status address is set to `IP:Port` instead of `0.0.0.0:Port`

**Comment by AstroProfundis** [comment]
It's working on v3.0.16, v3.1.2 and v4.0.1, not working since v4.0.2.

And I've narrowed the reproduce condition to:
 - TLS is configured in config file, and
 - The status address is set to an IP address different from that set in `--addr` (maybe only for the first start)

**Comment by AstroProfundis** [comment]
I've made few more tests and it looks like for v4.0.2-v4.0.4, the status port is always not binding on the first start if TLS is enabled, and it is working normally after a restart of tikv-server.

**Comment by hunterlxt** [comment]
I cannot reproduce the issue in my environment and here is my config:

pd.toml:
```
name = "pd"
data-dir = "data.pd"
client-urls = "https://127.0.0.1:10000"
peer-urls = "https://127.0.0.1:10001"
initial-cluster = "pd=https://127.0.0.1:10001"


[security]
cacert-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/root.crt"
cert-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/server.crt"
key-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/server.key"
```

tikv.toml:
```
[pd]
endpoints = ["127.0.0.1:10000"]

[server]
addr = "127.0.0.1:10002"
status-addr = "127.0.0.1:10003"

[storage]
data-dir = "data.tikv"

[security]
ca-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/root.crt"
cert-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/server.crt"
key-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/server.key"
```

**Comment by AstroProfundis** [comment]
Umm, I can only reproduce it with 3 or more PD nodes, and not using "127.0.0.1".

**Comment by hunterlxt** [comment]
Here is my modified config(`cat *.toml`):
```toml
name = "pd1"
data-dir = "data.pd1"
client-urls = "https://172.16.111.10:10000"
peer-urls = "https://172.16.111.10:10001"
initial-cluster = "pd1=https://172.16.111.10:10001,pd2=https://172.16.111.10:10005,pd3=https://172.16.111.10:10009"


[security]
cacert-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/root.crt"
cert-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/server.crt"
key-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/server.key"

name = "pd2"
data-dir = "data.pd2"
client-urls = "https://172.16.111.10:10004"
peer-urls = "https://172.16.111.10:10005"
initial-cluster = "pd1=https://172.16.111.10:10001,pd2=https://172.16.111.10:10005,pd3=https://172.16.111.10:10009"


[security]
cacert-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/root.crt"
cert-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/server.crt"
key-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/server.key"

name = "pd3"
data-dir = "data.pd3"
client-urls = "https://172.16.111.10:10008"
peer-urls = "https://172.16.111.10:10009"
initial-cluster = "pd1=https://172.16.111.10:10001,pd2=https://172.16.111.10:10005,pd3=https://172.16.111.10:10009"


[security]
cacert-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/root.crt"
cert-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/server.crt"
key-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/server.key"

[pd]
endpoints = ["172.16.111.10:10000"]

[server]
addr = "172.16.111.10:10002"
status-addr = "172.16.111.10:10003"

[storage]
data-dir = "data.tikv"

[security]
ca-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/root.crt"
cert-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/server.crt"
key-path = "/home/lxt/util/tidb-v4.0.4-linux-amd64/cert/server.key"
```
