### ISSUE TITLE
backup/restore via S3 using STS transiently fail with "Couldn't find AWS credentials in default sources or k8s environment"

### ISSUE THREAD

**Issue by kennytm** [tikv/tikv#8768]
### What version of TiKV are you using?

4.0.6

### What operating system and CPU are you using?

TiDB Operator v1.1.5

### Steps to reproduce

1) Prepare a table with 20 billion KV pairs with uncompressed total KV size of 3.5 TB (about 175 bytes per KV pair).

2) Configure an STS token of S3 write access with 24 hour expiry time. Mount the token to every TiKV Pod

```yaml
apiVersion: v1
kind: Pod
spec:
  containers:
  - ...
    image: pingcap/tikv:v4.0.6
    env:
      ...
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::111111111111:role/my-backup
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    volumeMounts:
      ...
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
  volumes:
  - name: aws-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token
```

3) Perform backup with command line 

```sh
./br backup full \
    --log-level=debug \
    --send-credentials-to-tikv=false \
    --storage=s3://backup-bucket/backup-prefix/ \
    --s3.region=us-west-2 \
    --s3.provider=aws \
    --pd=pd-addr:2379
```

### What did you expect?

Backup successful

### What did happened?

In some cases backup may fail early with the following log from BR, even if it is far before the expiry date.

```
[ERROR] [push.go:111] ["backup occur unknown error"] [error="Io(Custom { kind: Other, error: \"failed to put object Couldn\\'t find AWS credentials in default sources or k8s environment.\" })"] [stack="(irrelevant)"]

```
